### ISSUE TITLE
Show only rooms with one type of pet 

### ISSUE THREAD

**Issue by robertszczygielski** [PaulinaKoltun/pethotel#32]
In the view 'room list' add new drop menu, where we can select 'pet type' and only the rooms with this type should be showed in the list. This drop menu should be only in Animal Pet Type, menu should have possibility to select all type and one specific.

![pettypeonly](https://user-images.githubusercontent.com/11562290/44296912-2902ac00-a2c8-11e8-8b28-2e3de48f7b0d.png)

**Comment by PaulinaKoltun** [comment]
#34
